version: 0.0
os: linux
files:
  - source: /client/app/
    destination: /home/pi/Client
permissions:
  - object: /
    pattern: "**"
    owner: pi
    group: pi
hooks:
  ApplicationStop:
    - location: scripts/ApplicationStop.sh
      timeout: 60
      runas: pi
  BeforeInstall:
    - location: scripts/BeforeInstall.sh
      timeout: 300
      runas: pi
  AfterInstall:
    - location: scripts/AfterInstall.sh
      timeout: 300
      runas: pi
  ApplicationStart:
    - location: scripts/ApplicationStart.sh
      timeout: 60
      runas: pi
