version: 0.0
os: linux
files:
  - source: /app/
    destination: /home/bhavesh/Client
permissions:
  - object: /
    pattern: "**"
    owner: bhavesh
    group: bhavesh
hooks:
  ApplicationStop:
    - location: scripts/ApplicationStop.sh
      timeout: 60
      runas: bhavesh
  BeforeInstall:
    - location: scripts/BeforeInstall.sh
      timeout: 300
      runas: bhavesh
  AfterInstall:
    - location: scripts/AfterInstall.sh
      timeout: 300
      runas: bhavesh
  ApplicationStart:
    - location: scripts/ApplicationStart.sh
      timeout: 60
      runas: bhavesh
